title: Our friends squad
author: nityanand86876
email: nnt@nnt1.tk
description: This is a friend's website

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  nityanand86876 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
